version: '3.7'

services:

  db:
    image: rusdocker/postgres-5051:latest
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sonar-network

  sonarqube:
    image: rusdocker/sonarqube-5052:latest
    depends_on:
      - db
    user: sonarqube:sonarqube
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "8082:9000"
    networks:
      - sonar-network

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    user: pgadmin:pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: soportedesarrollo@riouruguay.com.ar
      PGADMIN_DEFAULT_PASSWORD: sonar
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
    networks:
      - sonar-network

networks:
  sonar-network:
    driver: bridge

